param(
    [string]$HtmlPath = "index.html",
    [string]$CssPath = "style.css"
)

$mappings = @(
    @("PC-LP", "landing-page")
    ,@("header", "site-header")
    ,@("bg", "site-header__bg")
    ,@("logo", "site-header__logo")
    ,@("rectangle", "site-header__logo-box")
    ,@("text-wrapper", "site-header__logo-text")
    ,@("CTA", "site-header__cta-phone")
    ,@("div", "site-header__cta-phone-bg")
    ,@("text-wrapper-2", "site-header__cta-phone-label")
    ,@("text-wrapper-3", "site-header__cta-phone-hours")
    ,@("text-wrapper-4", "site-header__cta-phone-number")
    ,@("img", "site-header__cta-icon")
    ,@("CTA-2", "site-header__cta-email")
    ,@("rectangle-2", "site-header__cta-email-box")
    ,@("text-wrapper-5", "site-header__cta-email-label")
    ,@("text-wrapper-6", "site-header__cta-email-hours")
    ,@("text-wrapper-7", "site-header__cta-email-link")
    ,@("FV", "hero-section")
    ,@("sub-copy", "hero-section__sub-copy")
    ,@("text-wrapper-8", "hero-section__sub-text")
    ,@("line", "hero-section__sub-line")
    ,@("catch-copy", "hero-section__catch")
    ,@("p", "hero-section__headline")
    ,@("span", "hero-section__text--bold")
    ,@("text-wrapper-9", "hero-section__text--married")
    ,@("text-wrapper-10", "hero-section__text--doubt")
    ,@("div-2", "hero-section__feelings")
    ,@("text-wrapper-11", "hero-section__text--accent")
    ,@("text-wrapper-12", "hero-section__text--normal")
    ,@("line-2", "hero-section__divider")
    ,@("div-3", "hero-section__support")
    ,@("text-wrapper-13", "hero-section__text--lawyer")
    ,@("view", "hero-section__features")
    ,@("view-2", "hero-section__feature")
    ,@("rectangle-3", "hero-section__feature-box")
    ,@("div-4", "hero-section__feature-text")
    ,@("text-wrapper-14", "hero-section__feature-label")
    ,@("text-wrapper-15", "hero-section__feature-em")
    ,@("ellipse", "hero-section__feature-icon-bg")
    ,@("rectangle-4", "hero-section__feature-icon")
    ,@("view-3", "hero-section__feature--remote")
    ,@("ellipse-2", "hero-section__feature-icon-bg")
    ,@("rectangle-5", "hero-section__feature-icon")
    ,@("OK-web", "hero-section__feature-text")
    ,@("text-wrapper-16", "hero-section__feature-label")
    ,@("text-wrapper-17", "hero-section__feature-sub")
    ,@("view-4", "hero-section__feature--private")
    ,@("rectangle-6", "hero-section__feature-icon")
    ,@("text-wrapper-18", "hero-section__feature-label")
    ,@("element", "hero-section__feature--anonymous")
    ,@("rectangle-7", "hero-section__feature-box--wide")
    ,@("ellipse-3", "hero-section__feature-icon-bg")
    ,@("rectangle-8", "hero-section__feature-icon")
    ,@("text-wrapper-19", "hero-section__feature-label")
    ,@("element-2", "hero-section__feature--specialist")
    ,@("ellipse-4", "hero-section__feature-icon-bg")
    ,@("text-wrapper-20", "hero-section__feature-label")
    ,@("view-5", "hero-section__banner")
    ,@("rectangle-9", "hero-section__banner-bg")
    ,@("text-wrapper-21", "hero-section__banner-text")
    ,@("view-6", "cta-section__banner")
    ,@("div-5", "cta-section__title")
    ,@("text-wrapper-22", "cta-section__title--free")
    ,@("text-wrapper-23", "cta-section__title--now")
    ,@("text-wrapper-24", "cta-section__badge")
    ,@("CTA-4", "cta-section__actions")
    ,@("CTA-5", "cta-section__phone")
    ,@("rectangle-10", "cta-section__phone-box")
    ,@("text-wrapper-25", "cta-section__phone-hours")
    ,@("text-wrapper-26", "cta-section__phone-number")
    ,@("rectangle-11", "cta-section__phone-icon")
    ,@("CTA-6", "cta-section__email")
    ,@("rectangle-12", "cta-section__email-box")
    ,@("text-wrapper-27", "cta-section__email-label")
    ,@("span-wrapper", "cta-section__email-sub")
    ,@("text-wrapper-28", "cta-section__email-sub-text")
    ,@("text-wrapper-29", "cta-section__email-link")
    ,@("rectangle-13", "cta-section__email-icon")
    ,@("CTA-3", "cta-section")
    ,@("CTA-7", "cta-section")
    ,@("CTA-8", "cta-section")
    ,@("CTA-9", "cta-section")
    ,@("CTA-10", "cta-section")
    ,@("CTA-11", "cta-section")
    ,@("CTA-12", "cta-section")
    ,@("view-7", "problems-section")
    ,@("bg-2", "problems-section__bg")
    ,@("rectangle-14", "problems-section__panel")
    ,@("h", "problems-section__heading")
    ,@("union", "problems-section__heading-bg")
    ,@("text-wrapper-30", "problems-section__heading-text")
    ,@("view-8", "problems-section__item")
    ,@("div-6", "problems-section__item-text")
    ,@("text-wrapper-31", "problems-section__text")
    ,@("text-wrapper-32", "problems-section__text--accent")
    ,@("line-3", "problems-section__item-line")
    ,@("ellipse-5", "problems-section__item-icon")
    ,@("view-9", "problems-section__item")
    ,@("view-10", "problems-section__item")
    ,@("view-11", "problems-section__item")
    ,@("div-7", "problems-section__item-text")
    ,@("view-12", "problems-section__item")
    ,@("view-13", "problems-section__item")
    ,@("view-14", "problems-section__item")
    ,@("view-15", "problems-section__item")
    ,@("view-16", "problems-section__item--last")
    ,@("ellipse-6", "problems-section__item-icon")
    ,@("span-wrapper-2", "problems-section__item-text")
    ,@("rectangle-15", "problems-section__note-box")
    ,@("rectangle-16", "problems-section__note-icon")
    ,@("div-8", "problems-section__note-text")
    ,@("text-wrapper-33", "problems-section__text")
    ,@("text-wrapper-34", "problems-section__text--accent")
    ,@("view-17", "about-section")
    ,@("rectangle-17", "about-section__bg-light")
    ,@("rectangle-18", "about-section__bg-image")
    ,@("view-18", "about-section__content")
    ,@("rectangle-19", "about-section__highlight")
    ,@("rectangle-20", "about-section__highlight")
    ,@("div-9", "about-section__text")
    ,@("text-wrapper-35", "about-section__text--semi")
    ,@("text-wrapper-36", "about-section__text--body")
    ,@("text-wrapper-37", "about-section__text--space")
    ,@("text-wrapper-38", "about-section__text--bold")
    ,@("text-wrapper-39", "about-section__text--married")
    ,@("text-wrapper-40", "about-section__text--large")
    ,@("text-wrapper-41", "about-section__text--small")
    ,@("bg-3", "about-section__attorney-bg")
    ,@("rectangle-21", "about-section__attorney-box")
    ,@("ellipse-7", "about-section__corner-dot")
    ,@("ellipse-8", "about-section__corner-dot")
    ,@("ellipse-9", "about-section__corner-dot")
    ,@("ellipse-10", "about-section__corner-dot")
    ,@("view-19", "about-section__attorney-desc")
    ,@("line-4", "about-section__underline")
    ,@("line-5", "about-section__underline")
    ,@("line-6", "about-section__underline")
    ,@("div-10", "about-section__attorney-text")
    ,@("text-wrapper-42", "about-section__attorney-name")
    ,@("text-wrapper-43", "about-section__attorney-name-sub")
    ,@("text-wrapper-44", "about-section__text--body")
    ,@("text-wrapper-45", "about-section__text--skill")
    ,@("text-wrapper-46", "about-section__text--space")
    ,@("text-wrapper-47", "about-section__text--quote")
    ,@("text-wrapper-48", "about-section__text--space")
    ,@("text-wrapper-49", "about-section__text--accent")
    ,@("image", "about-section__photo")
    ,@("element-removebg-preview", "about-section__stamp")
    ,@("view-20", "concerns-section")
    ,@("view-21", "concerns-section__intro")
    ,@("bg-4", "concerns-section__bg")
    ,@("view-22", "concerns-section__header-bar")
    ,@("rectangle-22", "concerns-section__header-bg")
    ,@("text-wrapper-50", "concerns-section__header-text")
    ,@("view-23", "concerns-section__image-block")
    ,@("element-m-removebg", "concerns-section__image")
    ,@("rectangle-23", "concerns-section__image-caption")
    ,@("view-24", "concerns-section__text-block")
    ,@("rectangle-24", "concerns-section__highlight")
    ,@("text-wrapper-51", "concerns-section__quote")
    ,@("rectangle-25", "concerns-section__highlight")
    ,@("rectangle-26", "concerns-section__highlight")
    ,@("text-wrapper-52", "concerns-section__quote")
    ,@("text-wrapper-53", "concerns-section__quote")
    ,@("text-wrapper-54", "concerns-section__desc")
    ,@("text-wrapper-55", "concerns-section__desc")
    ,@("div-11", "concerns-section__warning")
    ,@("text-wrapper-56", "concerns-section__text")
    ,@("text-wrapper-57", "concerns-section__text--em")
    ,@("div-12", "concerns-section__fact")
    ,@("text-wrapper-58", "concerns-section__text")
    ,@("text-wrapper-59", "concerns-section__text--em")
    ,@("text-wrapper-60", "concerns-section__desc")
    ,@("view-25", "concerns-section__definition")
    ,@("rectangle-27", "concerns-section__definition-bg")
    ,@("div-13", "concerns-section__definition-text")
    ,@("text-wrapper-61", "concerns-section__text--semi")
    ,@("text-wrapper-62", "concerns-section__text--body")
    ,@("text-wrapper-63", "concerns-section__text--em")
    ,@("ellipse-11", "concerns-section__dot")
    ,@("ellipse-12", "concerns-section__dot")
    ,@("ellipse-13", "concerns-section__dot")
    ,@("ellipse-14", "concerns-section__dot")
    ,@("view-26", "concerns-section__explanation")
    ,@("rectangle-28", "concerns-section__explanation-bg")
    ,@("ellipse-15", "concerns-section__explanation-photo")
    ,@("SNS", "concerns-section__sns-text")
    ,@("div-14", "concerns-section__legal-text")
    ,@("text-wrapper-64", "concerns-section__text")
    ,@("text-wrapper-65", "concerns-section__text--light")
    ,@("text-wrapper-66", "concerns-section__text--claim")
    ,@("text-wrapper-67", "concerns-section__text--claim-em")
    ,@("group", "concerns-section__rights-box")
    ,@("rectangle-29", "concerns-section__rights-bg")
    ,@("div-15", "concerns-section__rights-text")
    ,@("text-wrapper-68", "concerns-section__rights-title")
    ,@("text-wrapper-69", "concerns-section__text--space")
    ,@("text-wrapper-70", "concerns-section__text--em")
    ,@("text-wrapper-71", "concerns-section__text--body")
    ,@("text-wrapper-72", "concerns-section__text--space")
    ,@("text-wrapper-73", "concerns-section__text--body")
    ,@("element-removebg-preview-2", "concerns-section__rights-image")
    ,@("view-27", "concerns-section__warning-block")
    ,@("group-2", "concerns-section__warning-header")
    ,@("union-2", "concerns-section__warning-header-bg")
    ,@("rectangle-30", "concerns-section__warning-icon")
    ,@("text-wrapper-74", "concerns-section__warning-title")
    ,@("div-16", "concerns-section__warning-text")
    ,@("text-wrapper-75", "concerns-section__text--body")
    ,@("group-3", "concerns-section__example-box")
    ,@("rectangle-31", "concerns-section__example-bg")
    ,@("rectangle-32", "concerns-section__example-icon")
    ,@("rectangle-33", "concerns-section__example-icon")
    ,@("text-wrapper-76", "concerns-section__example-quote")
    ,@("div-17", "concerns-section__example-reply")
    ,@("text-wrapper-77", "concerns-section__text--body")
    ,@("text-wrapper-78", "concerns-section__text--empty")
    ,@("text-wrapper-79", "concerns-section__example-note")
    ,@("text-wrapper-80", "concerns-section__legal-note")
    ,@("div-18", "concerns-section__legal-note-text")
    ,@("text-wrapper-81", "concerns-section__text--bold")
    ,@("text-wrapper-82", "concerns-section__text--accent")
    ,@("text-wrapper-83", "concerns-section__legal-prefix")
    ,@("view-28", "concerns-section__factors")
    ,@("rectangle-34", "concerns-section__factors-bg")
    ,@("group-4", "concerns-section__factor-icon")
    ,@("group-5", "concerns-section__factor-icon")
    ,@("group-6", "concerns-section__factor-icon")
    ,@("text-wrapper-84", "concerns-section__factor-text")
    ,@("text-wrapper-85", "concerns-section__factor-text")
    ,@("text-wrapper-86", "concerns-section__factor-text")
    ,@("line-7", "concerns-section__factor-line")
    ,@("line-8", "concerns-section__factor-line")
    ,@("rectangle-35", "concerns-section__factor-bar")
    ,@("text-wrapper-87", "concerns-section__judgment")
    ,@("div-19", "concerns-section__protection")
    ,@("text-wrapper-88", "concerns-section__text--em")
    ,@("line-9", "concerns-section__divider")
    ,@("text-wrapper-89", "concerns-section__conclusion")
    ,@("text-wrapper-90", "concerns-section__cta-lead")
    ,@("group-7", "concerns-section__cta-box")
    ,@("rectangle-36", "concerns-section__cta-bg")
    ,@("line-10", "concerns-section__cta-line")
    ,@("line-11", "concerns-section__cta-line")
    ,@("text-wrapper-91", "concerns-section__cta-text")
    ,@("text-wrapper-92", "concerns-section__cta-body")
    ,@("div-20", "concerns-section__final-message")
    ,@("text-wrapper-93", "concerns-section__text--accent")
    ,@("view-29", "attorney-section")
    ,@("rectangle-37", "attorney-section__bg")
    ,@("view-30", "attorney-section__header")
    ,@("union-3", "attorney-section__header-bg")
    ,@("text-wrapper-94", "attorney-section__header-text")
    ,@("div-21", "attorney-section__name")
    ,@("text-wrapper-95", "attorney-section__name-text")
    ,@("text-wrapper-96", "attorney-section__name-text--em")
    ,@("view-31", "attorney-section__career")
    ,@("rectangle-38", "attorney-section__career-bg")
    ,@("element-3", "attorney-section__career-dates")
    ,@("text-wrapper-97", "attorney-section__career-events")
    ,@("line-12", "attorney-section__career-line")
    ,@("line-13", "attorney-section__career-line")
    ,@("line-14", "attorney-section__career-line--vertical")
    ,@("line-15", "attorney-section__career-line")
    ,@("line-16", "attorney-section__career-line")
    ,@("line-17", "attorney-section__career-line")
    ,@("line-18", "attorney-section__career-line")
    ,@("line-19", "attorney-section__career-line")
    ,@("view-32", "attorney-section__philosophy")
    ,@("union-wrapper", "attorney-section__philosophy-bg-wrap")
    ,@("union-4", "attorney-section__philosophy-bg")
    ,@("NPO", "attorney-section__philosophy-text")
    ,@("image-2", "attorney-section__photo")
    ,@("CLASSY-PC", "attorney-section__magazine")
    ,@("view-33", "benefits-section")
    ,@("view-34", "benefits-section__intro")
    ,@("group-wrapper", "benefits-section__header-wrap")
    ,@("group-8", "benefits-section__header")
    ,@("text-wrapper-98", "benefits-section__header-text")
    ,@("ellipse-16", "benefits-section__dot")
    ,@("ellipse-17", "benefits-section__dot")
    ,@("ellipse-18", "benefits-section__dot")
    ,@("ellipse-19", "benefits-section__dot")
    ,@("view-35", "benefits-section__card")
    ,@("rectangle-39", "benefits-section__card-bg")
    ,@("group-9", "benefits-section__card-quotes")
    ,@("rectangle-40", "benefits-section__card-highlight")
    ,@("rectangle-41", "benefits-section__card-highlight")
    ,@("rectangle-42", "benefits-section__card-highlight")
    ,@("text-wrapper-99", "benefits-section__card-quotes-text")
    ,@("div-22", "benefits-section__card-text")
    ,@("text-wrapper-100", "benefits-section__text--space")
    ,@("text-wrapper-101", "benefits-section__text--body")
    ,@("text-wrapper-102", "benefits-section__card-subtitle")
    ,@("text-wrapper-103", "benefits-section__card-title")
    ,@("ellipse-20", "benefits-section__dot--accent")
    ,@("ellipse-21", "benefits-section__dot--accent")
    ,@("ellipse-22", "benefits-section__dot--accent")
    ,@("ellipse-23", "benefits-section__dot--accent")
    ,@("view-36", "benefits-section__why")
    ,@("view-37", "benefits-section__why-heading")
    ,@("rectangle-43", "benefits-section__why-bg")
    ,@("text-wrapper-104", "benefits-section__why-text")
    ,@("image-3", "benefits-section__why-photo")
    ,@("group-10", "benefits-section__why-details")
    ,@("rectangle-44", "benefits-section__why-details-bg")
    ,@("group-11", "benefits-section__why-icon")
    ,@("group-12", "benefits-section__why-icon")
    ,@("group-13", "benefits-section__why-icon")
    ,@("rectangle-45", "benefits-section__why-bar")
    ,@("div-23", "benefits-section__why-text")
    ,@("text-wrapper-105", "benefits-section__text--em")
    ,@("text-wrapper-106", "benefits-section__text")
    ,@("text-wrapper-107", "benefits-section__text--small")
    ,@("text-wrapper-108", "benefits-section__text--strong")
    ,@("text-wrapper-109", "benefits-section__text--space")
    ,@("view-38", "benefits-section__points")
    ,@("h-2", "benefits-section__points-heading")
    ,@("rectangle-46", "section-heading__line")
    ,@("div-24", "benefits-section__points-title")
    ,@("text-wrapper-110", "benefits-section__text")
    ,@("text-wrapper-111", "benefits-section__text--accent")
    ,@("element-4", "benefits-section__point")
    ,@("text-wrapper-112", "benefits-section__point-number")
    ,@("ellipse-24", "benefits-section__point-circle")
    ,@("div-25", "benefits-section__point-text")
    ,@("text-wrapper-113", "benefits-section__text--strong")
    ,@("text-wrapper-114", "benefits-section__text--pink")
    ,@("rectangle-47", "benefits-section__point-icon")
    ,@("element-5", "benefits-section__point")
    ,@("div-26", "benefits-section__point-text")
    ,@("element-6", "benefits-section__point")
    ,@("div-27", "benefits-section__point-text")
    ,@("element-7", "benefits-section__point")
    ,@("div-28", "benefits-section__point-text")
    ,@("element-8", "benefits-section__point")
    ,@("div-29", "benefits-section__point-text")
    ,@("element-9", "benefits-section__point")
    ,@("view-39", "benefits-section__footer")
    ,@("line-20", "benefits-section__footer-line")
    ,@("div-30", "benefits-section__footer-text")
    ,@("text-wrapper-115", "benefits-section__text")
    ,@("text-wrapper-116", "benefits-section__text--accent")
    ,@("line-21", "benefits-section__footer-line")
    ,@("image-4", "benefits-section__photo")
    ,@("view-40", "reasons-section")
    ,@("h-3", "reasons-section__heading")
    ,@("text-wrapper-117", "reasons-section__heading-text")
    ,@("line-22", "reasons-section__heading-line")
    ,@("view-41", "reasons-section__card")
    ,@("group-14", "reasons-section__card-image")
    ,@("div-31", "reasons-section__card-text")
    ,@("text-wrapper-118", "reasons-section__text--bold")
    ,@("text-wrapper-119", "reasons-section__text--body")
    ,@("text-wrapper-120", "reasons-section__text--space")
    ,@("text-wrapper-121", "reasons-section__text--indent")
    ,@("text-wrapper-122", "reasons-section__text--strong")
    ,@("text-wrapper-123", "reasons-section__text--space")
    ,@("h-4", "reasons-section__card-heading")
    ,@("subtract", "reasons-section__card-number-bg")
    ,@("element-10", "reasons-section__card-number")
    ,@("text-wrapper-124", "reasons-section__card-label")
    ,@("text-wrapper-125", "reasons-section__card-number-text")
    ,@("text-wrapper-126", "reasons-section__card-title")
    ,@("line-23", "reasons-section__card-line")
    ,@("view-42", "reasons-section__card")
    ,@("rectangle-48", "reasons-section__card-bg")
    ,@("rectangle-49", "reasons-section__card-box")
    ,@("web-LINE-LINE", "reasons-section__card-text")
    ,@("text-wrapper-127", "reasons-section__text--body")
    ,@("text-wrapper-128", "reasons-section__text--accent")
    ,@("text-wrapper-129", "reasons-section__text--space")
    ,@("text-wrapper-130", "reasons-section__text--bold")
    ,@("text-wrapper-131", "reasons-section__text--strong")
    ,@("h-5", "reasons-section__card-heading")
    ,@("element-11", "reasons-section__card-number")
    ,@("text-wrapper-132", "reasons-section__card-title")
    ,@("view-43", "reasons-section__card")
    ,@("div-32", "reasons-section__card-text")
    ,@("h-6", "reasons-section__card-heading")
    ,@("element-12", "reasons-section__card-number")
    ,@("text-wrapper-133", "reasons-section__card-title")
    ,@("view-44", "pricing-section")
    ,@("h-7", "pricing-section__heading")
    ,@("rectangle-50", "section-heading__line")
    ,@("text-wrapper-134", "pricing-section__heading-text")
    ,@("rectangle-51", "section-heading__line")
    ,@("text-wrapper-135", "pricing-section__subtitle")
    ,@("view-45", "pricing-section__cta-bar")
    ,@("union-5", "pricing-section__cta-bg")
    ,@("element-13", "pricing-section__cta-text")
    ,@("text-wrapper-136", "pricing-section__text")
    ,@("text-wrapper-137", "pricing-section__text--em")
    ,@("text-wrapper-138", "pricing-section__text--small")
    ,@("view-46", "pricing-section__card")
    ,@("rectangle-52", "pricing-section__card-bg")
    ,@("div-33", "pricing-section__card-text")
    ,@("text-wrapper-139", "pricing-section__text--accent")
    ,@("group-15", "pricing-section__badge")
    ,@("union-6", "pricing-section__badge-bg")
    ,@("div-34", "pricing-section__badge-text")
    ,@("text-wrapper-140", "pricing-section__text--bold")
    ,@("text-wrapper-141", "pricing-section__text")
    ,@("text-wrapper-142", "pricing-section__text--empty")
    ,@("rectangle-53", "pricing-section__card-header")
    ,@("text-wrapper-143", "pricing-section__card-title")
    ,@("view-47", "pricing-section__table")
    ,@("rectangle-54", "pricing-section__table-border")
    ,@("element-14", "pricing-section__table-content")
    ,@("text-wrapper-144", "pricing-section__table-free")
    ,@("text-wrapper-145", "pricing-section__table-label")
    ,@("text-wrapper-146", "pricing-section__table-number")
    ,@("text-wrapper-147", "pricing-section__table-percent")
    ,@("text-wrapper-148", "pricing-section__table-tax")
    ,@("rectangle-55", "pricing-section__table-sidebar")
    ,@("text-wrapper-149", "pricing-section__table-row-label")
    ,@("line-24", "pricing-section__table-line")
    ,@("line-25", "pricing-section__table-line")
    ,@("line-26", "pricing-section__table-line")
    ,@("line-27", "pricing-section__table-line")
    ,@("view-48", "pricing-section__card--alt")
    ,@("rectangle-56", "pricing-section__card-bg")
    ,@("view-49", "pricing-section__table")
    ,@("text-wrapper-150", "pricing-section__table-number")
    ,@("text-wrapper-151", "pricing-section__table-unit")
    ,@("rectangle-57", "pricing-section__table-sidebar")
    ,@("text-wrapper-152", "pricing-section__table-tax--incl")
    ,@("text-wrapper-153", "pricing-section__table-tax--excl")
    ,@("rectangle-58", "pricing-section__card-header")
    ,@("text-wrapper-154", "pricing-section__card-title")
    ,@("div-35", "pricing-section__card-desc")
    ,@("text-wrapper-155", "pricing-section__text--strong")
    ,@("text-wrapper-156", "pricing-section__text")
    ,@("text-wrapper-157", "pricing-section__text--accent")
    ,@("group-16", "pricing-section__note")
    ,@("rectangle-59", "pricing-section__note-bg")
    ,@("text-wrapper-158", "pricing-section__note-text")
    ,@("view-50", "flow-section")
    ,@("h-8", "flow-section__heading")
    ,@("rectangle-60", "flow-section__heading-line")
    ,@("text-wrapper-159", "flow-section__heading-text")
    ,@("element-15", "flow-section__step")
    ,@("text-wrapper-160", "flow-section__text--accent")
    ,@("text-wrapper-161", "flow-section__text--note")
    ,@("text-wrapper-162", "flow-section__text")
    ,@("text-wrapper-163", "flow-section__text--em")
    ,@("web", "flow-section__step-text")
    ,@("text-wrapper-164", "flow-section__step-title")
    ,@("text-wrapper-165", "flow-section__step-number")
    ,@("rectangle-61", "flow-section__step-image")
    ,@("line-28", "flow-section__step-line")
    ,@("polygon", "flow-section__arrow")
    ,@("element-16", "flow-section__step")
    ,@("rectangle-62", "flow-section__step-bg")
    ,@("div-36", "flow-section__step-text")
    ,@("text-wrapper-166", "flow-section__text--pink")
    ,@("text-wrapper-167", "flow-section__step-title")
    ,@("text-wrapper-168", "flow-section__step-number")
    ,@("polygon-2", "flow-section__arrow")
    ,@("element-17", "flow-section__step")
    ,@("web-2", "flow-section__step-text")
    ,@("text-wrapper-169", "flow-section__step-title")
    ,@("STEP", "flow-section__step-number")
    ,@("polygon-3", "flow-section__arrow")
    ,@("element-18", "flow-section__step")
    ,@("rectangle-63", "flow-section__step-image")
    ,@("rectangle-64", "flow-section__step-bg")
    ,@("div-37", "flow-section__step-text")
    ,@("text-wrapper-170", "flow-section__step-title")
    ,@("STEP-2", "flow-section__step-number")
    ,@("rectangle-65", "flow-section__step-image")
    ,@("line-30", "flow-section__step-line")
    ,@("polygon-4", "flow-section__arrow")
    ,@("rectangle-66", "flow-section__step-bg")
    ,@("div-38", "flow-section__step-text")
    ,@("text-wrapper-171", "flow-section__step-title")
    ,@("STEP-3", "flow-section__step-number")
    ,@("rectangle-67", "flow-section__step-image")
    ,@("line-31", "flow-section__step-line")
    ,@("line-29", "flow-section__step-line")
    ,@("view-51", "faq-section")
    ,@("element-19", "faq-section__item")
    ,@("rectangle-68", "faq-section__question-bg")
    ,@("text-wrapper-172", "faq-section__question")
    ,@("union-7", "faq-section__toggle")
    ,@("rectangle-69", "faq-section__answer-bg")
    ,@("text-wrapper-173", "faq-section__answer")
    ,@("text-wrapper-174", "faq-section__answer-label")
    ,@("element-20", "faq-section__item")
    ,@("text-wrapper-175", "faq-section__question")
    ,@("rectangle-70", "faq-section__answer-bg")
    ,@("LINE", "faq-section__answer")
    ,@("text-wrapper-176", "faq-section__answer-label")
    ,@("element-21", "faq-section__item")
    ,@("text-wrapper-177", "faq-section__question")
    ,@("rectangle-71", "faq-section__answer-bg")
    ,@("text-wrapper-178", "faq-section__answer")
    ,@("element-22", "faq-section__item")
    ,@("text-wrapper-179", "faq-section__question")
    ,@("rectangle-72", "faq-section__answer-bg")
    ,@("LINE-2", "faq-section__answer")
    ,@("text-wrapper-180", "faq-section__answer-label")
    ,@("element-23", "faq-section__item")
    ,@("text-wrapper-181", "faq-section__question")
    ,@("rectangle-73", "faq-section__answer-bg")
    ,@("text-wrapper-182", "faq-section__answer")
    ,@("view-52", "message-section")
    ,@("rectangle-74", "message-section__bg")
    ,@("div-39", "message-section__text")
    ,@("text-wrapper-183", "message-section__body")
    ,@("text-wrapper-184", "message-section__space")
    ,@("image-5", "message-section__photo")
    ,@("view-53", "office-section")
    ,@("h-9", "office-section__heading")
    ,@("text-wrapper-185", "office-section__heading-text")
    ,@("view-54", "office-section__content")
    ,@("view-55", "office-section__sidebar")
    ,@("view-56", "office-section__details")
    ,@("line-32", "office-section__sidebar-line")
    ,@("line-33", "office-section__sidebar-line")
    ,@("element-a", "office-section__values")
    ,@("TEL-WEB", "office-section__labels")
    ,@("line-34", "office-section__detail-line")
    ,@("line-35", "office-section__detail-line")
    ,@("line-36", "office-section__detail-line")
    ,@("line-37", "office-section__detail-line")
    ,@("line-38", "office-section__detail-line")
    ,@("line-39", "office-section__detail-line")
    ,@("line-40", "office-section__detail-line")
    ,@("line-41", "office-section__detail-line")
    ,@("footer", "site-footer")
    ,@("rectangle-75", "site-footer__bg")
    ,@("text-wrapper-186", "site-footer__privacy")
    ,@("text-wrapper-187", "site-footer__copyright")
)

$sorted = $mappings | Sort-Object { $_[0].Length } -Descending

$htmlContent = Get-Content $HtmlPath -Raw -Encoding UTF8
$cssContent = Get-Content $CssPath -Raw -Encoding UTF8

function Replace-ClassNames([string]$content, [string]$pattern) {
    param($sortedMappings)
    foreach ($pair in $sortedMappings) {
        $oldName = [regex]::Escape($pair[0])
        $newName = $pair[1]
        if ($oldName -eq $newName) { continue }
        $content = [regex]::Replace($content, "\.$oldName(?=[\s\.\{,:])", ".$newName")
        $content = [regex]::Replace($content, 'class="([^"]*)"', {
            param($m)
            $value = $m.Groups[1].Value
            $classes = $value -split '\s+'
            $changed = $false
            for ($i = 0; $i -lt $classes.Count; $i++) {
                if ($classes[$i] -eq $pair[0]) {
                    $classes[$i] = $newName
                    $changed = $true
                }
            }
            if ($changed) { return 'class="' + ($classes -join ' ') + '"' }
            return $m.Value
        })
    }
    return $content
}

foreach ($pair in $sorted) {
    $oldName = [regex]::Escape($pair[0])
    $newName = $pair[1]
    if ($pair[0] -eq $pair[1]) { continue }
    $cssContent = [regex]::Replace($cssContent, "\.$oldName(?=[\s\.\{,:])", ".$newName")
}

foreach ($pair in $sorted) {
    $oldName = $pair[0]
    $newName = $pair[1]
    if ($oldName -eq $newName) { continue }
    $htmlContent = [regex]::Replace($htmlContent, 'class="([^"]*)"', {
        param($m)
        $value = $m.Groups[1].Value
        $classes = $value -split '\s+'
        $changed = $false
        for ($i = 0; $i -lt $classes.Count; $i++) {
            if ($classes[$i] -eq $oldName) {
                $classes[$i] = $newName
                $changed = $true
            }
        }
        if ($changed) { return 'class="' + ($classes -join ' ') + '"' }
        return $m.Value
    })
}

Set-Content -Path $HtmlPath -Value $htmlContent -Encoding UTF8 -NoNewline
Set-Content -Path $CssPath -Value $cssContent -Encoding UTF8 -NoNewline
Write-Host "BEM refactor complete: $($sorted.Count) mappings applied"
