param(
    [string]$HtmlPath = "index.html",
    [string]$CssPath = "style.css"
)

# ========== CLASS NAME MAPPING ==========
# Array of [oldName, newName] pairs (ordered by length descending to avoid partial matches)
$mappings = @(
    # ---- Main container ----
    ,@("PC-LP", "landing-page")

    # ---- Header ----
    ,@("header", "header")
    ,@("bg", "header-bg")
    ,@("logo", "logo")
    ,@("rectangle", "logo-bg")
    ,@("text-wrapper", "logo-text")
    ,@("CTA", "header-cta-phone")
    ,@("div", "header-cta-phone-bg")
    ,@("text-wrapper-2", "header-cta-phone-title")
    ,@("text-wrapper-3", "header-cta-phone-hours")
    ,@("text-wrapper-4", "header-cta-phone-number")
    ,@("img", "header-cta-phone-icon")
    ,@("CTA-2", "header-cta-email")
    ,@("rectangle-2", "header-cta-email-bg")
    ,@("text-wrapper-5", "header-cta-email-title")
    ,@("text-wrapper-6", "header-cta-email-hours")
    ,@("text-wrapper-7", "header-cta-email-link")

    # ---- Hero (FV) ----
    ,@("FV", "hero")
    ,@("sub-copy", "hero-sub-copy")
    ,@("text-wrapper-8", "hero-sub-text")
    ,@("line", "hero-sub-line")
    ,@("catch-copy", "hero-catch-copy")
    ,@("p", "hero-catch-text")
    ,@("span", "hero-em-bold")
    ,@("text-wrapper-9", "hero-married")
    ,@("text-wrapper-10", "hero-doubt")
    ,@("div-2", "hero-feelings")
    ,@("text-wrapper-11", "hero-feeling-em")
    ,@("text-wrapper-12", "hero-feeling-normal")
    ,@("line-2", "hero-divider")
    ,@("div-3", "hero-support")
    ,@("text-wrapper-13", "hero-support-lawyer")
    ,@("view", "hero-features")
    ,@("view-2", "hero-feature-free")
    ,@("rectangle-3", "hero-feature-bg")
    ,@("div-4", "hero-feature-text")
    ,@("text-wrapper-14", "hero-feature-label")
    ,@("text-wrapper-15", "hero-feature-em")
    ,@("ellipse", "hero-feature-dot")
    ,@("rectangle-4", "hero-feature-icon-1")
    ,@("view-3", "hero-feature-remote")
    ,@("ellipse-2", "hero-feature-dot-2")
    ,@("rectangle-5", "hero-feature-icon-2")
    ,@("OK-web", "hero-feature-remote-text")
    ,@("text-wrapper-16", "hero-remote-label")
    ,@("text-wrapper-17", "hero-remote-sub")
    ,@("view-4", "hero-feature-private")
    ,@("rectangle-6", "hero-feature-icon-3")
    ,@("text-wrapper-18", "hero-private-text")
    ,@("element", "hero-feature-anonymous")
    ,@("rectangle-7", "hero-feature-bg-2")
    ,@("ellipse-3", "hero-feature-dot-3")
    ,@("rectangle-8", "hero-feature-icon-4")
    ,@("text-wrapper-19", "hero-anonymous-text")
    ,@("element-2", "hero-feature-specialist")
    ,@("ellipse-4", "hero-feature-dot-4")
    ,@("text-wrapper-20", "hero-specialist-text")
    ,@("view-5", "hero-banner")
    ,@("rectangle-9", "hero-banner-bg")
    ,@("text-wrapper-21", "hero-banner-text")

    # ---- CTA Banner (shared) ----
    ,@("view-6", "cta-banner")
    ,@("div-5", "cta-title")
    ,@("text-wrapper-22", "cta-free")
    ,@("text-wrapper-23", "cta-now")
    ,@("text-wrapper-24", "cta-first")
    ,@("CTA-4", "cta-buttons")
    ,@("CTA-5", "cta-phone")
    ,@("rectangle-10", "cta-phone-bg")
    ,@("text-wrapper-25", "cta-phone-hours")
    ,@("text-wrapper-26", "cta-phone-number")
    ,@("rectangle-11", "cta-phone-icon")
    ,@("CTA-6", "cta-email")
    ,@("rectangle-12", "cta-email-bg")
    ,@("text-wrapper-27", "cta-email-title")
    ,@("span-wrapper", "cta-email-sub")
    ,@("text-wrapper-28", "cta-email-sub-text")
    ,@("text-wrapper-29", "cta-email-link")
    ,@("rectangle-13", "cta-email-icon")

    # ---- CTA sections ----
    ,@("CTA-3", "cta-section-1")
    ,@("CTA-7", "cta-section-2")
    ,@("CTA-8", "cta-section-3")
    ,@("CTA-9", "cta-section-4")
    ,@("CTA-10", "cta-section-5")
    ,@("CTA-11", "cta-section-6")
    ,@("CTA-12", "cta-section-7")

    # ---- Section: Problems (view-7) ----
    ,@("view-7", "section-problems")
    ,@("bg-2", "problems-bg")
    ,@("rectangle-14", "problems-box")
    ,@("h", "problems-heading")
    ,@("union", "problems-heading-bg")
    ,@("text-wrapper-30", "problems-heading-text")
    ,@("view-8", "problems-item-1")
    ,@("div-6", "problems-item-text")
    ,@("text-wrapper-31", "problems-text-normal")
    ,@("text-wrapper-32", "problems-text-em")
    ,@("line-3", "problems-item-line")
    ,@("ellipse-5", "problems-item-icon")
    ,@("view-9", "problems-item-2")
    ,@("view-10", "problems-item-3")
    ,@("view-11", "problems-item-4")
    ,@("div-7", "problems-item-text-alt")
    ,@("view-12", "problems-item-5")
    ,@("view-13", "problems-item-6")
    ,@("view-14", "problems-item-7")
    ,@("view-15", "problems-item-8")
    ,@("view-16", "problems-item-9")
    ,@("ellipse-6", "problems-item-icon-2")
    ,@("span-wrapper-2", "problems-item-text-2")
    ,@("rectangle-15", "problems-note-box")
    ,@("rectangle-16", "problems-note-icon")
    ,@("div-8", "problems-note-text")
    ,@("text-wrapper-33", "problems-note-normal")
    ,@("text-wrapper-34", "problems-note-em")

    # ---- Section: About (view-17) ----
    ,@("view-17", "section-about")
    ,@("rectangle-17", "about-bg-light")
    ,@("rectangle-18", "about-bg-image")
    ,@("view-18", "about-content")
    ,@("rectangle-19", "about-highlight-1")
    ,@("rectangle-20", "about-highlight-2")
    ,@("div-9", "about-text")
    ,@("text-wrapper-35", "about-text-semi")
    ,@("text-wrapper-36", "about-text-body")
    ,@("text-wrapper-37", "about-text-space")
    ,@("text-wrapper-38", "about-text-bold")
    ,@("text-wrapper-39", "about-text-married")
    ,@("text-wrapper-40", "about-text-large-em")
    ,@("text-wrapper-41", "about-text-small")
    ,@("bg-3", "about-attorney-bg")
    ,@("rectangle-21", "about-attorney-box")
    ,@("ellipse-7", "about-corner-dot-1")
    ,@("ellipse-8", "about-corner-dot-2")
    ,@("ellipse-9", "about-corner-dot-3")
    ,@("ellipse-10", "about-corner-dot-4")
    ,@("view-19", "about-attorney-desc")
    ,@("line-4", "about-underline-1")
    ,@("line-5", "about-underline-2")
    ,@("line-6", "about-underline-3")
    ,@("div-10", "about-attorney-text")
    ,@("text-wrapper-42", "about-attorney-name")
    ,@("text-wrapper-43", "about-attorney-name-sub")
    ,@("text-wrapper-44", "about-attorney-body")
    ,@("text-wrapper-45", "about-attorney-skill")
    ,@("text-wrapper-46", "about-attorney-space")
    ,@("text-wrapper-47", "about-attorney-quote")
    ,@("text-wrapper-48", "about-attorney-quote-space")
    ,@("text-wrapper-49", "about-attorney-em")
    ,@("image", "about-photo")
    ,@("element-removebg-preview", "about-stamp")

    # ---- Section: Concerns (view-20) ----
    ,@("view-20", "section-concerns")
    ,@("view-21", "concerns-header-block")
    ,@("bg-4", "concerns-bg")
    ,@("view-22", "concerns-header-bar")
    ,@("rectangle-22", "concerns-header-bg")
    ,@("text-wrapper-50", "concerns-header-text")
    ,@("view-23", "concerns-image-block")
    ,@("element-m-removebg", "concerns-image")
    ,@("rectangle-23", "concerns-image-caption")
    ,@("view-24", "concerns-text-block")
    ,@("rectangle-24", "concerns-text-highlight-1")
    ,@("text-wrapper-51", "concerns-quote-1")
    ,@("rectangle-25", "concerns-text-highlight-2")
    ,@("rectangle-26", "concerns-text-highlight-3")
    ,@("text-wrapper-52", "concerns-quote-2")
    ,@("text-wrapper-53", "concerns-quote-3")
    ,@("text-wrapper-54", "concerns-desc-1")
    ,@("text-wrapper-55", "concerns-desc-2")
    ,@("div-11", "concerns-warning")
    ,@("text-wrapper-56", "concerns-warning-normal")
    ,@("text-wrapper-57", "concerns-warning-em")
    ,@("div-12", "concerns-fact")
    ,@("text-wrapper-58", "concerns-fact-normal")
    ,@("text-wrapper-59", "concerns-fact-em")
    ,@("text-wrapper-60", "concerns-continue")
    ,@("view-25", "concerns-definition")
    ,@("rectangle-27", "concerns-definition-bg")
    ,@("div-13", "concerns-definition-text")
    ,@("text-wrapper-61", "concerns-definition-semi")
    ,@("text-wrapper-62", "concerns-definition-body")
    ,@("text-wrapper-63", "concerns-definition-em")
    ,@("ellipse-11", "concerns-definition-dot-1")
    ,@("ellipse-12", "concerns-definition-dot-2")
    ,@("ellipse-13", "concerns-definition-dot-3")
    ,@("ellipse-14", "concerns-definition-dot-4")
    ,@("view-26", "concerns-explanation")
    ,@("rectangle-28", "concerns-explanation-bg")
    ,@("ellipse-15", "concerns-explanation-photo")
    ,@("SNS", "concerns-sns-text")
    ,@("div-14", "concerns-legal-text")
    ,@("text-wrapper-64", "concerns-legal-normal")
    ,@("text-wrapper-65", "concerns-legal-light")
    ,@("text-wrapper-66", "concerns-legal-claim")
    ,@("text-wrapper-67", "concerns-legal-claim-em")
    ,@("group", "concerns-rights-box")
    ,@("rectangle-29", "concerns-rights-bg")
    ,@("div-15", "concerns-rights-text")
    ,@("text-wrapper-68", "concerns-rights-title")
    ,@("text-wrapper-69", "concerns-rights-space")
    ,@("text-wrapper-70", "concerns-rights-em")
    ,@("text-wrapper-71", "concerns-rights-body")
    ,@("text-wrapper-72", "concerns-rights-space-2")
    ,@("text-wrapper-73", "concerns-rights-text-2")
    ,@("element-removebg-preview-2", "concerns-rights-image")
    ,@("view-27", "concerns-warning-block")
    ,@("group-2", "concerns-warning-header")
    ,@("union-2", "concerns-warning-header-bg")
    ,@("rectangle-30", "concerns-warning-icon")
    ,@("text-wrapper-74", "concerns-warning-title")
    ,@("div-16", "concerns-warning-text")
    ,@("text-wrapper-75", "concerns-text-body")
    ,@("group-3", "concerns-example-box")
    ,@("rectangle-31", "concerns-example-bg")
    ,@("rectangle-32", "concerns-example-icon-1")
    ,@("rectangle-33", "concerns-example-icon-2")
    ,@("text-wrapper-76", "concerns-example-quote")
    ,@("div-17", "concerns-example-reply")
    ,@("text-wrapper-77", "concerns-example-reply-text")
    ,@("text-wrapper-78", "concerns-example-reply-empty")
    ,@("text-wrapper-79", "concerns-example-note")
    ,@("text-wrapper-80", "concerns-legal-note")
    ,@("div-18", "concerns-legal-note-text")
    ,@("text-wrapper-81", "concerns-legal-note-space")
    ,@("text-wrapper-82", "concerns-legal-note-em")
    ,@("text-wrapper-83", "concerns-legal-note-prefix")
    ,@("view-28", "concerns-factors")
    ,@("rectangle-34", "concerns-factors-bg")
    ,@("group-4", "concerns-factor-icon-1")
    ,@("group-5", "concerns-factor-icon-2")
    ,@("group-6", "concerns-factor-icon-3")
    ,@("text-wrapper-84", "concerns-factor-text-1")
    ,@("text-wrapper-85", "concerns-factor-text-2")
    ,@("text-wrapper-86", "concerns-factor-text-3")
    ,@("line-7", "concerns-factor-line-1")
    ,@("line-8", "concerns-factor-line-2")
    ,@("rectangle-35", "concerns-factor-bar")
    ,@("text-wrapper-87", "concerns-judgment")
    ,@("div-19", "concerns-protection")
    ,@("text-wrapper-88", "concerns-protection-em")
    ,@("line-9", "concerns-final-divider")
    ,@("text-wrapper-89", "concerns-conclusion")
    ,@("text-wrapper-90", "concerns-cta-lead")
    ,@("group-7", "concerns-cta-box")
    ,@("rectangle-36", "concerns-cta-bg")
    ,@("line-10", "concerns-cta-line-1")
    ,@("line-11", "concerns-cta-line-2")
    ,@("text-wrapper-91", "concerns-cta-text")
    ,@("text-wrapper-92", "concerns-cta-body")
    ,@("div-20", "concerns-final-message")
    ,@("text-wrapper-93", "concerns-final-em")

    # ---- Section: Attorney Profile (view-29) ----
    ,@("view-29", "section-attorney")
    ,@("rectangle-37", "attorney-bg")
    ,@("view-30", "attorney-header")
    ,@("union-3", "attorney-header-bg")
    ,@("text-wrapper-94", "attorney-header-text")
    ,@("div-21", "attorney-name")
    ,@("text-wrapper-95", "attorney-name-normal")
    ,@("text-wrapper-96", "attorney-name-em")
    ,@("view-31", "attorney-career")
    ,@("rectangle-38", "attorney-career-bg")
    ,@("element-3", "attorney-career-dates")
    ,@("text-wrapper-97", "attorney-career-events")
    ,@("line-12", "attorney-career-line-1")
    ,@("line-13", "attorney-career-line-2")
    ,@("line-14", "attorney-career-line-v")
    ,@("line-15", "attorney-career-line-3")
    ,@("line-16", "attorney-career-line-4")
    ,@("line-17", "attorney-career-line-5")
    ,@("line-18", "attorney-career-line-6")
    ,@("line-19", "attorney-career-line-7")
    ,@("view-32", "attorney-philosophy")
    ,@("union-wrapper", "attorney-philosophy-bg")
    ,@("union-4", "attorney-philosophy-union")
    ,@("NPO", "attorney-philosophy-text")
    ,@("image-2", "attorney-photo")
    ,@("CLASSY-PC", "attorney-magazine")

    # ---- Section: Benefits (view-33) ----
    ,@("view-33", "section-benefits")
    ,@("view-34", "benefits-header")
    ,@("group-wrapper", "benefits-header-wrapper")
    ,@("group-8", "benefits-header-group")
    ,@("text-wrapper-98", "benefits-header-text")
    ,@("ellipse-16", "benefits-header-dot-1")
    ,@("ellipse-17", "benefits-header-dot-2")
    ,@("ellipse-18", "benefits-header-dot-3")
    ,@("ellipse-19", "benefits-header-dot-4")
    ,@("view-35", "benefits-card")
    ,@("rectangle-39", "benefits-card-bg")
    ,@("group-9", "benefits-card-quotes")
    ,@("rectangle-40", "benefits-card-hl-1")
    ,@("rectangle-41", "benefits-card-hl-2")
    ,@("rectangle-42", "benefits-card-hl-3")
    ,@("text-wrapper-99", "benefits-card-quotes-text")
    ,@("div-22", "benefits-card-text")
    ,@("text-wrapper-100", "benefits-card-space")
    ,@("text-wrapper-101", "benefits-card-body")
    ,@("text-wrapper-102", "benefits-card-subtitle")
    ,@("text-wrapper-103", "benefits-card-title")
    ,@("ellipse-20", "benefits-card-dot-1")
    ,@("ellipse-21", "benefits-card-dot-2")
    ,@("ellipse-22", "benefits-card-dot-3")
    ,@("ellipse-23", "benefits-card-dot-4")
    ,@("view-36", "benefits-why")
    ,@("view-37", "benefits-why-heading")
    ,@("rectangle-43", "benefits-why-bg")
    ,@("text-wrapper-104", "benefits-why-text")
    ,@("image-3", "benefits-why-photo")
    ,@("group-10", "benefits-why-details")
    ,@("rectangle-44", "benefits-why-details-bg")
    ,@("group-11", "benefits-why-icon-1")
    ,@("group-12", "benefits-why-icon-2")
    ,@("group-13", "benefits-why-icon-3")
    ,@("rectangle-45", "benefits-why-bar")
    ,@("div-23", "benefits-why-text")
    ,@("text-wrapper-105", "benefits-why-em")
    ,@("text-wrapper-106", "benefits-why-normal")
    ,@("text-wrapper-107", "benefits-why-small")
    ,@("text-wrapper-108", "benefits-why-strong")
    ,@("text-wrapper-109", "benefits-space")
    ,@("view-38", "benefits-points")
    ,@("h-2", "benefits-points-heading")
    ,@("rectangle-46", "benefits-points-line")
    ,@("div-24", "benefits-points-title")
    ,@("text-wrapper-110", "benefits-points-normal")
    ,@("text-wrapper-111", "benefits-points-em")
    ,@("element-4", "benefits-point-1")
    ,@("text-wrapper-112", "benefits-point-number")
    ,@("ellipse-24", "benefits-point-circle")
    ,@("div-25", "benefits-point-text-1")
    ,@("text-wrapper-113", "benefits-point-strong")
    ,@("text-wrapper-114", "benefits-point-pink")
    ,@("rectangle-47", "benefits-point-icon")
    ,@("element-5", "benefits-point-2")
    ,@("div-26", "benefits-point-text-2")
    ,@("element-6", "benefits-point-3")
    ,@("div-27", "benefits-point-text-3")
    ,@("element-7", "benefits-point-4")
    ,@("div-28", "benefits-point-text-4")
    ,@("element-8", "benefits-point-5")
    ,@("div-29", "benefits-point-text-5")
    ,@("element-9", "benefits-point-6")
    ,@("view-39", "benefits-footer")
    ,@("line-20", "benefits-footer-line-top")
    ,@("div-30", "benefits-footer-text")
    ,@("text-wrapper-115", "benefits-footer-normal")
    ,@("text-wrapper-116", "benefits-footer-em")
    ,@("line-21", "benefits-footer-line-bottom")
    ,@("image-4", "benefits-photo")

    # ---- Section: Reasons (view-40) ----
    ,@("view-40", "section-reasons")
    ,@("h-3", "reasons-heading")
    ,@("text-wrapper-117", "reasons-heading-text")
    ,@("line-22", "reasons-heading-line")
    ,@("view-41", "reasons-card-1")
    ,@("group-14", "reasons-card-1-image")
    ,@("div-31", "reasons-card-1-text")
    ,@("text-wrapper-118", "reasons-card-1-bold")
    ,@("text-wrapper-119", "reasons-card-1-body")
    ,@("text-wrapper-120", "reasons-card-1-space")
    ,@("text-wrapper-121", "reasons-card-1-indent")
    ,@("text-wrapper-122", "reasons-card-1-strong")
    ,@("text-wrapper-123", "reasons-card-1-space-2")
    ,@("h-4", "reasons-card-1-heading")
    ,@("subtract", "reasons-card-1-number-bg")
    ,@("element-10", "reasons-card-1-number")
    ,@("text-wrapper-124", "reasons-card-1-label")
    ,@("text-wrapper-125", "reasons-card-1-number-text")
    ,@("text-wrapper-126", "reasons-card-1-title")
    ,@("line-23", "reasons-card-line")
    ,@("view-42", "reasons-card-2")
    ,@("rectangle-48", "reasons-card-bg")
    ,@("rectangle-49", "reasons-card-2-box")
    ,@("web-LINE-LINE", "reasons-card-2-text")
    ,@("text-wrapper-127", "reasons-text-body")
    ,@("text-wrapper-128", "reasons-text-em")
    ,@("text-wrapper-129", "reasons-text-space")
    ,@("text-wrapper-130", "reasons-text-bold")
    ,@("text-wrapper-131", "reasons-text-strong")
    ,@("h-5", "reasons-card-2-heading")
    ,@("element-11", "reasons-card-2-number")
    ,@("text-wrapper-132", "reasons-card-2-title")
    ,@("view-43", "reasons-card-3")
    ,@("div-32", "reasons-card-3-text")
    ,@("h-6", "reasons-card-3-heading")
    ,@("element-12", "reasons-card-3-number")
    ,@("text-wrapper-133", "reasons-card-3-title")

    # ---- Section: Pricing (view-44) ----
    ,@("view-44", "section-pricing")
    ,@("h-7", "pricing-heading")
    ,@("rectangle-50", "section-heading-line-top")
    ,@("text-wrapper-134", "pricing-heading-text")
    ,@("rectangle-51", "section-heading-line-bottom")
    ,@("text-wrapper-135", "pricing-subtitle")
    ,@("view-45", "pricing-cta-bar")
    ,@("union-5", "pricing-cta-bg")
    ,@("element-13", "pricing-cta-text")
    ,@("text-wrapper-136", "pricing-cta-body")
    ,@("text-wrapper-137", "pricing-cta-em")
    ,@("text-wrapper-138", "pricing-cta-small")
    ,@("view-46", "pricing-card-left")
    ,@("rectangle-52", "pricing-card-left-bg")
    ,@("div-33", "pricing-card-left-text")
    ,@("text-wrapper-139", "pricing-card-left-em")
    ,@("group-15", "pricing-card-left-badge")
    ,@("union-6", "pricing-badge-bg")
    ,@("div-34", "pricing-badge-text")
    ,@("text-wrapper-140", "pricing-badge-bold")
    ,@("text-wrapper-141", "pricing-badge-normal")
    ,@("text-wrapper-142", "pricing-badge-empty")
    ,@("rectangle-53", "pricing-card-left-header")
    ,@("text-wrapper-143", "pricing-card-left-title")
    ,@("view-47", "pricing-table-left")
    ,@("rectangle-54", "pricing-table-border")
    ,@("element-14", "pricing-table-content")
    ,@("text-wrapper-144", "pricing-table-free")
    ,@("text-wrapper-145", "pricing-table-label")
    ,@("text-wrapper-146", "pricing-table-number")
    ,@("text-wrapper-147", "pricing-table-percent")
    ,@("text-wrapper-148", "pricing-table-tax-excl")
    ,@("rectangle-55", "pricing-table-sidebar")
    ,@("text-wrapper-149", "pricing-table-row-label")
    ,@("line-24", "pricing-table-line-1")
    ,@("line-25", "pricing-table-line-2")
    ,@("line-26", "pricing-table-line-3")
    ,@("line-27", "pricing-table-line-4")
    ,@("view-48", "pricing-card-right")
    ,@("rectangle-56", "pricing-card-right-bg")
    ,@("view-49", "pricing-table-right")
    ,@("text-wrapper-150", "pricing-table-number-2")
    ,@("text-wrapper-151", "pricing-table-unit")
    ,@("rectangle-57", "pricing-table-sidebar-2")
    ,@("text-wrapper-152", "pricing-table-tax-incl")
    ,@("text-wrapper-153", "pricing-table-tax-label")
    ,@("rectangle-58", "pricing-card-right-header")
    ,@("text-wrapper-154", "pricing-card-right-title")
    ,@("div-35", "pricing-card-right-desc")
    ,@("text-wrapper-155", "pricing-desc-strong")
    ,@("text-wrapper-156", "pricing-desc-normal")
    ,@("text-wrapper-157", "pricing-desc-em")
    ,@("group-16", "pricing-note")
    ,@("rectangle-59", "pricing-note-bg")
    ,@("text-wrapper-158", "pricing-note-text")

    # ---- Section: Flow (view-50) ----
    ,@("view-50", "section-flow")
    ,@("h-8", "flow-heading")
    ,@("rectangle-60", "flow-heading-line")
    ,@("text-wrapper-159", "flow-heading-text")
    ,@("element-15", "flow-step-1")
    ,@("text-wrapper-160", "flow-text-em")
    ,@("text-wrapper-161", "flow-text-note")
    ,@("text-wrapper-162", "flow-text-body")
    ,@("text-wrapper-163", "flow-text-em-alt")
    ,@("web", "flow-step-1-text")
    ,@("text-wrapper-164", "flow-step-1-title")
    ,@("text-wrapper-165", "flow-step-1-number")
    ,@("rectangle-61", "flow-step-image")
    ,@("line-28", "flow-step-line-1")
    ,@("polygon", "flow-arrow-1")
    ,@("element-16", "flow-step-2")
    ,@("rectangle-62", "flow-step-2-bg")
    ,@("div-36", "flow-step-2-text")
    ,@("text-wrapper-166", "flow-text-pink")
    ,@("text-wrapper-167", "flow-step-2-title")
    ,@("text-wrapper-168", "flow-step-2-number")
    ,@("polygon-2", "flow-arrow-2")
    ,@("element-17", "flow-step-3")
    ,@("web-2", "flow-step-3-text")
    ,@("text-wrapper-169", "flow-step-3-title")
    ,@("STEP", "flow-step-3-number")
    ,@("polygon-3", "flow-arrow-3")
    ,@("element-18", "flow-step-4")
    ,@("rectangle-63", "flow-step-image-2")
    ,@("rectangle-64", "flow-step-4-bg")
    ,@("div-37", "flow-step-4-text")
    ,@("text-wrapper-170", "flow-step-4-title")
    ,@("STEP-2", "flow-step-4-number")
    ,@("rectangle-65", "flow-step-image-4")
    ,@("line-30", "flow-step-line-4")
    ,@("polygon-4", "flow-arrow-4")
    ,@("rectangle-66", "flow-step-5-bg")
    ,@("div-38", "flow-step-5-text")
    ,@("text-wrapper-171", "flow-step-5-title")
    ,@("STEP-3", "flow-step-5-number")
    ,@("rectangle-67", "flow-step-image-5")
    ,@("line-31", "flow-step-line-5")
    ,@("line-29", "flow-step-line-2")

    # ---- Section: FAQ (view-51) ----
    ,@("view-51", "section-faq")
    ,@("element-19", "faq-item-1")
    ,@("rectangle-68", "faq-question-bg")
    ,@("text-wrapper-172", "faq-question-1")
    ,@("union-7", "faq-toggle")
    ,@("rectangle-69", "faq-answer-bg-1")
    ,@("text-wrapper-173", "faq-answer-1")
    ,@("text-wrapper-174", "faq-answer-label-1")
    ,@("element-20", "faq-item-2")
    ,@("text-wrapper-175", "faq-question-2")
    ,@("rectangle-70", "faq-answer-bg-2")
    ,@("LINE", "faq-answer-2")
    ,@("text-wrapper-176", "faq-answer-label")
    ,@("element-21", "faq-item-3")
    ,@("text-wrapper-177", "faq-question-3")
    ,@("rectangle-71", "faq-answer-bg-3")
    ,@("text-wrapper-178", "faq-answer-3")
    ,@("element-22", "faq-item-4")
    ,@("text-wrapper-179", "faq-question-4")
    ,@("rectangle-72", "faq-answer-bg-4")
    ,@("LINE-2", "faq-answer-4")
    ,@("text-wrapper-180", "faq-answer-label-4")
    ,@("element-23", "faq-item-5")
    ,@("text-wrapper-181", "faq-question-5")
    ,@("rectangle-73", "faq-answer-bg-5")
    ,@("text-wrapper-182", "faq-answer-5")

    # ---- Section: Message (view-52) ----
    ,@("view-52", "section-message")
    ,@("rectangle-74", "message-bg")
    ,@("div-39", "message-text")
    ,@("text-wrapper-183", "message-body")
    ,@("text-wrapper-184", "message-space")
    ,@("image-5", "message-photo")

    # ---- Section: Office (view-53) ----
    ,@("view-53", "section-office")
    ,@("h-9", "office-heading")
    ,@("text-wrapper-185", "office-heading-text")
    ,@("view-54", "office-content")
    ,@("view-55", "office-sidebar")
    ,@("view-56", "office-details")
    ,@("line-32", "office-sidebar-line-1")
    ,@("line-33", "office-sidebar-line")
    ,@("element-a", "office-values")
    ,@("TEL-WEB", "office-labels")
    ,@("line-34", "office-detail-line-1")
    ,@("line-35", "office-detail-line-2")
    ,@("line-36", "office-detail-line-3")
    ,@("line-37", "office-detail-line-4")
    ,@("line-38", "office-detail-line-5")
    ,@("line-39", "office-detail-line-6")
    ,@("line-40", "office-detail-line-7")
    ,@("line-41", "office-detail-line-8")

    # ---- Footer ----
    ,@("footer", "footer")
    ,@("rectangle-75", "footer-bg")
    ,@("text-wrapper-186", "footer-privacy")
    ,@("text-wrapper-187", "footer-copyright")
)

Write-Host "Mapping has $($mappings.Length) entries"

# Sort by old name length descending to avoid partial-match corruption
$sorted = $mappings | Sort-Object { $_[0].Length } -Descending

# Read files
$htmlContent = Get-Content $HtmlPath -Raw
$cssContent = Get-Content $CssPath -Raw

Write-Host "Read HTML: $($htmlContent.Length) chars"
Write-Host "Read CSS: $($cssContent.Length) chars"

$totalReplacements = 0
# HTML-only: process class names with whole-word matching
foreach ($pair in $sorted) {
    $oldName = $pair[0]
    $newName = $pair[1]
    if ($oldName -eq $newName) { continue }
    
    $htmlMatches = 0
    $htmlContent = [regex]::Replace($htmlContent, 'class="([^"]*)"', {
        param($m)
        $value = $m.Groups[1].Value
        if ($value -eq $oldName -or $value -like "*$oldName*") {
            $classes = $value -split '\s+'
            $changed = $false
            for ($i = 0; $i -lt $classes.Count; $i++) {
                if ($classes[$i] -eq $oldName) {
                    $classes[$i] = $newName
                    $changed = $true
                    $htmlMatches++
                }
            }
            if ($changed) {
                return 'class="' + ($classes -join ' ') + '"'
            }
        }
        return $m.Value  # no change
    })
    
    if ($htmlMatches -gt 0) {
        $totalReplacements += $htmlMatches
        Write-Host "  $oldName -> $newName (HTML:$htmlMatches)"
    }
}

Write-Host "Total replacements: $totalReplacements"

# Write HTML back
Set-Content -Path $HtmlPath -Value $htmlContent -Encoding UTF8 -NoNewline

# CSS: already renamed, just update root class
Write-Host "Updating CSS root class: .PC-LP -> .landing-page"
$cssContent = $cssContent -replace '(?<=\.)PC-LP(?=[\s\.\{,])', 'landing-page'
Set-Content -Path $CssPath -Value $cssContent -Encoding UTF8 -NoNewline

Write-Host "Done!"
